### ISSUE TITLE
Just two minor remarks

### ISSUE THREAD

**Issue by Gerungofulus** [ipatate/gdpr-cookies#2]
Hey, 

first and foremost: Thanks for that great tool! I've been looking for something like this quite a while and it made my life way easier! I only have two remarks:

- I struggled for a moment or two because it wouldn't save the "accept all cookies" setting in case no cookies are added. In this case the banner just always reappears. I thought I was doing something wrong until I added a cookie. 
- Would it be possible to add a bool flag indicating whether or not to show an additional group "mandatory" with just a description of which data is saved by the cookies the user can't opt out from and a switch than cannot be disabled?

Thanks again for your tool! I already created a PR adding German translation as I'm not that much of a JS geek :)

**Comment by ipatate** [comment]
hello, sorry i had not seen the issues. i look your remarks and the bug when no cookie are added, thanks

**Comment by ipatate** [comment]
ok, it's corrected for the bug if no cookies are added.
I look for add service mandatory
